src/snark/constraints.rs
An upstream repo detects that the original handling of limbs is not compatible with the new nonnative gadget.
=> Fix range overflow in SNARK input constraints

Cargo.toml, cp-benches/Cargo.toml, cp-benches/benches/crypto_primitives/comm.rs, cp-benches/benches/crypto_primitives/crh.rs, cp-benches/benches/crypto_primitives/prf.rs, cp-benches/benches/crypto_primitives/signature.rs, src/commitment/blake2s/constraints.rs, src/commitment/blake2s/mod.rs, src/commitment/injective_map/constraints.rs, src/commitment/injective_map/mod.rs, src/commitment/mod.rs, src/commitment/pedersen/mod.rs, src/crh/bowe_hopwood/constraints.rs, src/crh/bowe_hopwood/mod.rs, src/crh/injective_map/mod.rs, src/crh/mod.rs, src/crh/pedersen/constraints.rs, src/crh/pedersen/mod.rs, src/merkle_tree/constraints.rs, src/merkle_tree/mod.rs, src/prf/blake2s/constraints.rs, src/prf/blake2s/mod.rs, src/signature/mod.rs, src/signature/schnorr/mod.rs
This PR makes a number of changes:
1. bump up the versions of Blake2s and Digest.
2. replace `rand` with `ark_std::rand`.
3. remove `rand_xorshift` from the tests.
=> Replace `rand` with `ark_std::rand`

Cargo.toml, src/snark/constraints.rs
Nonnative now no longer uses the density-optimized feature and requires this information to be passed directly. 
As a result, if a library uses the `get_params` function directly, it will now need to research the optimization goal (by looking at the ConstraintSystem's optimization goal).
This closes #25
=> Synchronize with the change in nonnative

src/snark/constraints.rs
cc @Will-Lin4 as this might require you to do a `cargo update`.
The nonnative adds a field `cs` to enable tracking the optimization type for constant, allocated variables. This PR reconciles with that change.
=> Update `NonNativeFieldInputVar` to match the upstream update

src/crh/poseidon/constraints.rs
When doing an PR downstream for `pcd`, we found that the Poseidon CRH may trigger `no_std` issues. This PR provides a simple patch.
Note that, in many of our repos, `no_std` only runs for `no-default-features`, which excludes R1CS. We may need to revise the CI YAML file to capture the R1CS feature. This would be a longer discussion dedicated to the `template` repo.
=> Make Poseidon CRH `no_std`

src/merkle_tree/constraints.rs
I forgot to include `ark_std::vec::Vec` in merkle-tree/constraints. Sorry
This PR will fix that issue
Closes: #39
=> Fix no_std issue for merkle tree constraints

.github/workflows/ci.yml, src/encryption/elgamal/constraints.rs
Our existing CI tests for `no_std` always run on `--no-default-features` and therefore it does not capture the case of R1CS. 
This PR fixes the `no_std` issue and also lets the no_std test covers the case with the R1CS feature. Our other repos likely need a similar treatment. 
This closes #51
=> Fix `no_std` when the R1CS feature is on

CHANGELOG.md, src/crh/bowe_hopwood/constraints.rs, src/crh/bowe_hopwood/mod.rs, src/merkle_tree/constraints.rs
This implements `TwoToOneCRH` for Bowe-Hopwood. You can now use B-H over Jubjub for circuit land Merkle tree membership proofs.
---
=> Made Bowe-Hopwood Usable as a Merkle Tree Hash

src/merkle_tree/constraints.rs
There are two ways to convert a field element to bytes: `to_bytes`, and `to_bytes_unchecked`. The former enforces that the bytes represent an integer whose value is less than the field modulus, while the latter does not (it only performs booleanity checks). While `to_bytes` is generally the preferred option because it provides safety checks by default, in the context of a Merkle tree it is inefficient to use it due to the additional check.
Rather, we can use `to_bytes_unchecked` here, because if the prover provides a bad bit-representation, the root of the Merkle tree will be different, which will cause the constraint system to fail.
---
checked off. If any of the checklist items are not applicable, …
=> Use `to_non_unique_bytes` in Merkle tree constraints

src/merkle_tree/constraints.rs, src/merkle_tree/mod.rs
The `derive` of `Clone` trait for `Path<P>` doesn't work well, because it implicitly adds a trait bound `P: Copy`. In most cases, when `clone`ing a path, user might encounter the following compile error: 
```
the following trait bounds were not satisfied:
`P: Clone`
which is required by `ark_crypto_primitives::Path<P>: Clone`
```
This PR removes the `derive` and implements `Clone` trait ~~manually~~ using `Derivative` instead.  Also added `Clone` for constraint path. 
---
=> Fix `Clone` for Merkle Tree Path

src/merkle_tree/mod.rs
The current merkle tree code assumes that the merkle tree height is greater than 1 (has at least two leaves). Otherwise the code will panic: https://github.com/arkworks-rs/crypto-primitives/blob/main/src/merkle_tree/mod.rs#L352. 
While it is debatable whether the merkle tree should support size 1 merkle tree. The implementation should at least make this assumption explicit.
(for example, it will cause the problem like https://github.com/Manta-Network/manta-crypto/pull/23)
closes: #XXXX
---
=> forbid size 1 merkle tree

.github/workflows/ci.yml, CHANGELOG.md, src/merkle_tree/constraints.rs, src/merkle_tree/tests/constraints.rs
Currently, for `PathVar`, the location information is encoded by `path: Vec<Boolean>` and `leaf_is_right_child: Boolean` (chaining those two get the big endian encoding of index of leaf). 
There are indeed many circumstances where we also have constraints on leaf position (take IOP verifier's query as an example). For now, `path` and `leaf_is_right_child` are just variables created from `Boolean::new_variable`, and user do not have access to such those variables. In this commit, user will be able to: 
- get the leaf index variable in `PathVar` and constrain them
- replace the leaf index variable in `PathVar` with their own variable (possibly already with some constraints)
---
checked off. If any of the …
=> Allow user to set leaf position for `PathVar`

src/crh/sha256/constraints.rs
Fixes a bug in the `EqGadget` implementation of `crh::sha256::DigestVar`. I wrote a regression test that demonstrates the bug.
Didn't bother adding a changelog entry because the SHA256 entry is still pending. You can think of this as part of that.
---
=> Fixed SHA256 digest EqGadget bug; included regression test

Cargo.toml
Since a PR in ark-sponge is merged and the corresponding branch is deleted, Cargo.toml is no longer able to find that branch. This PR fixes so.
Closes #82
---
=> Fix the dependency of ark-sponge in Cargo.toml

CHANGELOG.md, src/crh/pedersen/mod.rs
Two-line change. I have a `write_to_file<S: CanonicalSerialize>(filename: &Path, data: &S)` function, but I can't use it with Pedersen parameters. This fixes that problem.
=> Impl `CanonicalSerialize` and `CanonicalDeserialize` for `pedersen::Parameters`

src/sponge/absorb.rs
Fix the comment that does not match the code in `src/sponge/absorb.rs` line 68:
"Append the list to `dest`." -> "Return the list as `Vec`."
As the function `batch_to_sponge_field_elements_as_vec` returns `Vec`, 
the changed comment is more appropriate.
=> Fix comment that does not match the code

src/sponge/mod.rs, src/sponge/poseidon/constraints.rs
=> fix `num_bits` always returning full size

.github/workflows/mdlinter.yml, src/sponge/absorb.rs
… basefields are prime fields.
closes: #XXXX
---
=> Fix `impl Absorb for SWAffine/TEAffine` to not require `P::BaseField: PrimeField`

Cargo.toml, src/sponge/absorb.rs
With the current implementation of Poseidon, when trying to absorb a field element from a different field of sponge, there is no error and the developer would think everything is right :) The `unwrap` helps with making panics.
Also, I changed the repos from `curves` to `algebra`.
---
=> Fix bug in `Absorb` and update `Cargo.toml`

src/merkle_tree/mod.rs
Absorbing the Merkle tree digest is a common operation.
It'll save us writing: `Config::InnerDigest: Absorb` or `&to_bytes!(&root)`
closes: #XXXX
---
=> Absorb for MT digest

crypto-primitives/src/sponge/poseidon/constraints.rs, crypto-primitives/src/sponge/poseidon/mod.rs, crypto-primitives/src/sponge/poseidon/tests.rs
Poseidion sponge skips a permutation in a certain condition:
* Sponge is in squeeze mode
* Number of elements in the call equals to the rate
So that it returns same elements in subsequent calls which is demonstrated in the first commit of this PR. Problem is fixed in the next commit. I also added a simpler independent implementation to apply cross fuzz test and must be removed when this PR matures.  I've checked and asked around if any production project uses `PoseidonSponge` at the moment but don't see any and I think this PR is safe to be opened.
I also come across another strange behaviour which I feel that it is not intended. In a such condition:
* Sponge is in squeeze mode
* Number of elements int the call equals to zero
* Internal index is factor of rate but not zero
It applies a …
=> Fix poseidon sponge bug

crypto-primitives/src/merkle_tree/mod.rs, crypto-primitives/src/snark/constraints.rs, crypto-primitives/src/sponge/constraints/absorb.rs
Cleans a bunch of warnings emitted during `cargo doc`, and resolves some unresolved links.
---
=> Cleanup docs

crypto-primitives/src/merkle_tree/constraints.rs, crypto-primitives/src/merkle_tree/mod.rs
The changes in commit 0960300 were to satisfy CI for the nightly build. It is no longer an issue. Also, it is better to bring the struct `IdentityDigestConverter` back as some users depend on it.
---
=> Undo changes in `0960300`
